#!/bin/bash
# Run API

echo "nohup.out cleared. Server will now start."
echo "-----------------------------------------"
nohup python3 server.py > logs.txt &
echo "API Server running. Get requests can now be made."
echo "-------------------------------------------------"
